import React, { Component } from 'react'
import styledComponents from 'styled-components'

const WrapperSpiner = styledComponents.div
`

@keyframes ldio-4ja6u2wlhcc {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-4ja6u2wlhcc div {
  position: absolute;
  animation: ldio-4ja6u2wlhcc 1s linear infinite;
  width: 133.64px;
  height: 133.64px;
  top: 61.67999999999999px;
  left: calc(50% - 63.64px);
  border-radius: 50%;
  box-shadow: 0 7.196000000000001px 0 0 #2414ec;
  transform-origin: 66.82px 70.41799999999999px;
}
.loadingio-spinner-eclipse-49qq1axkarc {
  width: 257px;
  height: 257px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-4ja6u2wlhcc {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-4ja6u2wlhcc div { box-sizing: content-box; }
/* generated by https://loading.io/ */`

export default class Spinner extends Component {
  render() {
    return (
      <WrapperSpiner className="loadingio-spinner-eclipse-49qq1axkarc"><div className="ldio-4ja6u2wlhcc">
<div></div>
</div></WrapperSpiner>
    )
  }
}
